[toolchain]
channel = "1.80.1"
# The supported toolchains used to build the project
targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "riscv64gc-unknown-linux-gnu",
]

